import React from 'react';
import { Link } from 'react-router-dom';

const TermsPage = () => {
  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-100 to-gray-200 py-12">
      <div className="max-w-4xl mx-auto px-6">
        {/* Header */}
        <div className="mb-10 text-center">
          <h1 className="text-4xl font-extrabold text-gray-900">Terms of Service</h1>
          <p className="text-gray-600 mt-2">Last Updated: September 14, 2025</p>
          <Link 
            to="/" 
            className="mt-4 inline-flex items-center text-[#7D1C4A] hover:text-[#670D2F] font-medium"
          >
            ← Back to Home
          </Link>
        </div>

        {/* Content */}
        <div className="bg-white rounded-2xl shadow-md p-10 border border-gray-100 leading-relaxed">
          <p className="text-gray-700 mb-6">
            Welcome to Interview Prep AI. By using our service, you agree to these terms.
          </p>

          {/* Sections */}
          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4 border-l-4 border-[#7D1C4A] pl-3">
            1. What We Do
          </h2>
          <p className="text-gray-700 mb-6">
            Interview Prep AI generates interview questions based on job descriptions you provide using Google's Gemini AI.
          </p>

          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4 border-l-4 border-[#7D1C4A] pl-3">
            2. Your Account
          </h2>
          <ul className="list-disc pl-6 space-y-0.5 text-gray-700 mb-6">
            <li>Provide accurate information when signing up</li>
            <li>Keep your login details secure</li>
            <li>You're responsible for all activity on your account</li>
          </ul>

          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4 border-l-4 border-[#7D1C4A] pl-3">
            3. How to Use Our Service
          </h2>
          <div className="mb-6">
            <p className="text-gray-700 font-medium mb-2">You can:</p>
            <ul className="list-disc pl-6 space-y-0.5 text-gray-700 mb-4">
              <li>Submit job descriptions to get relevant interview questions</li>
              <li>Use generated questions for interview preparation</li>
              <li>Access your question history</li>
            </ul>
            
            <p className="text-gray-700 font-medium mb-2">You cannot:</p>
            <ul className="list-disc pl-6 space-y-0.5 text-gray-700">
              <li>Share your account with others</li>
              <li>Use the service for illegal purposes</li>
              <li>Try to copy or reverse engineer our system</li>
            </ul>
          </div>

          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4 border-l-4 border-[#7D1C4A] pl-3">
            4. AI-Generated Content
          </h2>
          <ul className="list-disc pl-6 space-y-0.5 text-gray-700 mb-6">
            <li>Questions are generated by AI and may not be perfect</li>
            <li>Use them as a guide, not as guaranteed interview questions</li>
            <li>We don't promise you'll get the exact questions in real interviews</li>
          </ul>

          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4 border-l-4 border-[#7D1C4A] pl-3">
            5. Payment
          </h2>
          <ul className="list-disc pl-6 space-y-0.5 text-gray-700 mb-6">
            <li>Subscription fees are charged monthly/yearly</li>
            <li>No refunds except as required by law</li>
            <li>Free trial converts to paid unless you cancel</li>
          </ul>

          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4 border-l-4 border-[#7D1C4A] pl-3">
            6. Your Data
          </h2>
          <div className="mb-6">
            <p className="text-gray-700 mb-2">We collect:</p>
            <ul className="list-disc pl-6 space-y-0.5 text-gray-700 mb-4">
              <li>Account info (name, email)</li>
              <li>Job descriptions you submit</li>
              <li>Generated questions and your usage</li>
            </ul>
            <p className="text-gray-700">
              We use this to provide and improve our service. See our{" "}
              <Link to="/privacy" className="text-[#7D1C4A] hover:underline">
                Privacy Policy
              </Link>{" "}
              for details.
            </p>
          </div>

          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4 border-l-4 border-[#7D1C4A] pl-3">
            7. Cancellation
          </h2>
          <p className="text-gray-700 mb-6">
            You can cancel anytime. We can terminate accounts that violate these terms.
          </p>

          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4 border-l-4 border-[#7D1C4A] pl-3">
            8. Limitations
          </h2>
          <ul className="list-disc pl-6 space-y-0.5 text-gray-700 mb-6">
            <li>We're not responsible if AI generates inappropriate content</li>
            <li>No guarantee of interview success</li>
            <li>Service may be temporarily unavailable for maintenance</li>
          </ul>

          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4 border-l-4 border-[#7D1C4A] pl-3">
            9. Changes
          </h2>
          <p className="text-gray-700 mb-6">
            We may update these terms. Continued use means you accept changes.
          </p>

          <h2 className="text-2xl font-semibold text-gray-900 mt-8 mb-4 border-l-4 border-[#7D1C4A] pl-3">
            10. Contact
          </h2>
          <p className="text-gray-700 mb-6">
            Questions? Email us at:{" "}
            <a 
              href="mailto:support@interviewprepai.com" 
              className="text-[#7D1C4A] hover:underline font-medium"
            >
              support@interviewprepai.com
            </a>
          </p>

          <div className="border-t border-gray-200 pt-6 mt-8">
            <p className="text-gray-600 italic text-sm text-center">
              By using Interview Prep AI, you agree to these Terms of Service.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default TermsPage;
